CREATE DATABASE piedrasportsdb;
USE piedrasportsdb;
CREATE TABLE ROLES (
    ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    NOMBRE VARCHAR(20) NOT NULL
);
CREATE TABLE PROVEEDORES (
    ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    NOMBRE VARCHAR(50) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL,
    MOVIL VARCHAR(15) NOT NULL
);
CREATE TABLE PRODUCTOS(
    ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    NOMBRE VARCHAR(50) NOT NULL,
    PRECIO FLOAT NOT NULL,
    MARCA VARCHAR(50) NOT NULL,
    DESCRIPCION VARCHAR(150) NULL
);
CREATE TABLE USUARIOS (
    NOMBRE VARCHAR(20) PRIMARY KEY NOT NULL,
    CONTRASENA VARCHAR(12) NOT NULL,
    ROL INT NOT NULL,
    FOREIGN KEY (ROL) REFERENCES ROLES(ID)
);
CREATE TABLE CLIENTES (
    ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    NOMBRE VARCHAR(50) NOT NULL,
    APELLIDO VARCHAR(50) NOT NULL,
    DIRECCION VARCHAR(150) NOT NULL,
    EMAIL VARCHAR(50) NOT NULL,
    USUARIO VARCHAR(20) NOT NULL,
    FOREIGN KEY (USUARIO) REFERENCES USUARIOS(NOMBRE)
);
CREATE TABLE EMPLEADOS(
    ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    NOMBRE VARCHAR(100) NOT NULL,
    FECHA_INGRESO DATETIME NOT NULL,
    EMAIL VARCHAR(100) NOT NULL,
    MOVIL VARCHAR(15) NOT NULL,
    DIRECCION VARCHAR(150) NOT NULL,
    USUARIO VARCHAR(20) NOT NULL,
    FOREIGN KEY (USUARIO) REFERENCES USUARIOS(NOMBRE)
);
CREATE TABLE COMPRAS(
    ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    PRECIO FLOAT NOT NULL,
    FECHA DATETIME NOT NULL,
    ESTADO VARCHAR(20) NOT NULL,
    PROVEEDOR INT NOT NULL,
    FOREIGN KEY (PROVEEDOR) REFERENCES PROVEEDORES(ID)
);
CREATE TABLE DETALLE_COMPRA(
    COMPRA_ID INT NOT NULL,
    PRODUCTO_ID INT NOT NULL,
    CANTIDAD INT NOT NULL,
    PRECIO_UNITARIO FLOAT NOT NULL,
    PRIMARY KEY (COMPRA_ID, PRODUCTO_ID),
    FOREIGN KEY (COMPRA_ID) REFERENCES COMPRAS(ID),
    FOREIGN KEY (PRODUCTO_ID) REFERENCES PRODUCTOS(ID)
);
CREATE TABLE PEDIDOS(
    ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    FECHA DATETIME NOT NULL,
    CANTIDAD INT NOT NULL,
    DESCRIPCION VARCHAR(150) NULL,
    FECHA_ENTREGA DATETIME NULL,
    FORMA_DE_PAGO VARCHAR(30) NOT NULL,
    CLIENTE INT NOT NULL,
    FOREIGN KEY (CLIENTE) REFERENCES CLIENTES(ID)
);
CREATE TABLE DETALLE_PEDIDO(
    PEDIDO_ID INT NOT NULL,
    PRODUCTO_ID INT NOT NULL,
    FOREIGN KEY (PEDIDO_ID) REFERENCES PEDIDOS(ID),
    FOREIGN KEY (PRODUCTO_ID) REFERENCES PRODUCTOS(ID)
);
CREATE TABLE VALORACIONES(
    ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    NUMERO DOUBLE NOT NULL,
    DESCRIPCION VARCHAR(150) NULL,
    PEDIDO INT NOT NULL,
    FOREIGN KEY (PEDIDO) REFERENCES PEDIDOS(ID)
);
CREATE TABLE DETALLE_PRODUCTO(
    EMPLEADO_ID INT NOT NULL,
    PRODUCTO_ID INT NOT NULL,
    FOREIGN KEY (EMPLEADO_ID) REFERENCES EMPLEADOS(ID),
    FOREIGN KEY (PRODUCTO_ID) REFERENCES PRODUCTOS(ID)
);
CREATE TABLE DISTRIBUCIONES(
    ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    FECHA_INICIO DATETIME NOT NULL,
    FECHA_FIN DATETIME NOT NULL,
    PEDIDO INT NOT NULL,
    FOREIGN KEY (PEDIDO) REFERENCES PEDIDOS(ID)
);
CREATE TABLE VENTAS(
    ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    PRECIO_TOTAL FLOAT NOT NULL,
    PRECIO_UNITARIO FLOAT NOT NULL,
    CANTIDAD_PRODUCTO INT NOT NULL,
    FORMA_DE_PAGO VARCHAR(30) NOT NULL,
    FECHA DATETIME NOT NULL,
    PEDIDO INT NOT NULL,
    EMPLEADO INT NOT NULL,
    FOREIGN KEY (PEDIDO) REFERENCES PEDIDOS(ID),
    FOREIGN KEY (EMPLEADO) REFERENCES EMPLEADOS(ID)
);